#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

PROG=/usr/sbin/phtunnel
PIDFILE=/var/run/phtunnel.pid
LOGFILE=/var/log/oraybox/phtunnel.log

start_service() {
    local enabled
    config_load phtunnel
    config_get enabled core enabled

    [ "$enabled" != "1" ] && return 0

    mkdir -p /var/log/oraybox

    procd_open_instance
    procd_set_param command $PROG
    procd_set_param pidfile $PIDFILE
    procd_set_param file /etc/config/phtunnel
    procd_set_param stdout $LOGFILE
    procd_set_param stderr $LOGFILE
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}

stop_service() {
    service_stop $PROG
    [ -f "$PIDFILE" ] && rm -f "$PIDFILE"
}

reload_service() {
    stop
    start
}
