include $(TOPDIR)/rules.mk

# OpenWrt 25.12.x APK 包构建系统

# APK 构建变量
APK_BUILD_DIR:=$(PKG_BUILD_DIR)/apk-build
APK_INSTALL_DIR:=$(PKG_BUILD_DIR)/apk-install

# APK 元数据函数
define Build/WritePKGINFO
	$(INSTALL_DIR) $(dir $(1))
	echo "#$$Header" > $(1)
	echo "# Generated by OpenWrt Build System" >> $(1)
	echo "" >> $(1)
	echo "pkgname = $(PKG_NAME)" >> $(1)
	echo "pkgver = $(APK_VERSION)" >> $(1)
	echo "pkgdesc = $(APK_DESCRIPTION)" >> $(1)
	echo "url = $(APK_URL)" >> $(1)
	echo "builddate = $$(date -u +%Y%m%d%H%M%S)" >> $(1)
	echo "packager = $(APK_MAINTAINER)" >> $(1)
	echo "size = $$(du -sb $(APK_INSTALL_DIR) 2>/dev/null | cut -f1)" >> $(1)
	echo "arch = $(APK_ARCH)" >> $(1)
	echo "license = $(APK_LICENSE)" >> $(1)
	echo "maintainer = $(APK_MAINTAINER)" >> $(1)
	echo "origin = $(APK_ORIGIN)" >> $(1)
endef

# APK 构建目标
define Build/APK
	# 创建构建目录
	$(INSTALL_DIR) $(APK_BUILD_DIR)
	$(INSTALL_DIR) $(APK_INSTALL_DIR)

	# 安装文件到 APK 目录
	$(call Package/$(PKG_NAME)/install,$(APK_INSTALL_DIR))

	# 生成 .PKGINFO 文件
	$(call Build/WritePKGINFO,$(APK_BUILD_DIR)/.PKGINFO)

	# 创建 APK 包
	$(TAR) -czf $(PKG_BUILD_DIR)/$(PKG_NAME)-$(APK_VERSION)_$(APK_ARCH).apk \
		-C $(APK_BUILD_DIR) .PKGINFO \
		-C $(APK_INSTALL_DIR) .
endef

# APK 清理
define Build/APK/Clean
	rm -rf $(APK_BUILD_DIR)
	rm -rf $(APK_INSTALL_DIR)
	rm -f $(PKG_BUILD_DIR)/$(PKG_NAME)-$(APK_VERSION)_$(APK_ARCH).apk
endef
