name: Build PHTunnel APK

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - name: x86_64
            sdk_target: x86
            sdk_subtarget: 64
            pkg_arch: x86_64
          - name: aarch64
            sdk_target: aarch64
            sdk_subtarget: generic
            pkg_arch: aarch64
          - name: armv7
            sdk_target: arm
            sdk_subtarget: cortex-a7
            pkg_arch: armv7
          - name: mips
            sdk_target: mips
            sdk_subtarget: 24kc
            pkg_arch: mips
          - name: mipsel
            sdk_target: mipsel
            sdk_subtarget: 24kc
            pkg_arch: mipsel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 unzip rsync subversion \
            xsltproc zlib1g-dev

      - name: Test
        run: echo "Building for ${{ matrix.name }}"

      - name: Test Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.name }}
          path: README.md
